CREATE TABLE "DATA_CUSTOMER" (
	"CODE_CLIENT" integer NOT NULL,
	"NAME_LASTNAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"LOCATION" VARCHAR(255),
	"CONNECTIONS" VARCHAR(255),
	"JOB_TITLE" VARCHAR(255),
	"COMPANY_NAME" VARCHAR(255),
	"JOB_DURATION" VARCHAR(255),
	"COLLEGES" VARCHAR(255),
	"DEGREES" VARCHAR(255),
	"CERTIFICATIONS" VARCHAR(255),
	"FLAGGED" integer DEFAULT '0',
	"TIMESTAMP" TIMESTAMP,
	"EMAIL" VARCHAR(255),
	"DURATION" VARCHAR(255),
	"PROFILE_LINK" VARCHAR(255),
	CONSTRAINT "DATA_CUSTOMER_pk" PRIMARY KEY ("CODE_CLIENT")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "DATA_CREDIT" (
	"DATA_CREDIT_PK" serial NOT NULL,
	"RECID_" VARCHAR(255) NOT NULL UNIQUE,
	"REF_CREDIT_" VARCHAR(255),
	"DATE_GENERATION_" integer,
	"MONTANT_" DECIMAL,
	CONSTRAINT "DATA_CREDIT_pk" PRIMARY KEY ("DATA_CREDIT_PK")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "DATA_ACCOUNT" (
	"DATA_ACCOUNT_PK" serial NOT NULL,
	"ID_ACCOUNT" VARCHAR(25) UNIQUE,
	CONSTRAINT "DATA_ACCOUNT_pk" PRIMARY KEY ("DATA_ACCOUNT_PK")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "DATA_NBR_MVT" (
	"NBR_MVT" integer,
	"DATA_NBR_MVT_PK" serial,
	"CODE_CLIENT" integer NOT NULL UNIQUE,
	CONSTRAINT "DATA_NBR_MVT_pk" PRIMARY KEY ("DATA_NBR_MVT_PK")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "CLIENT_SCORE" (
	"CODE_CLIENT" integer NOT NULL,
	"DATA_CREDIT_PK" integer,
	"DATA_ACCOUNT_PK" integer,
	"DATA_NBR_MVT_PK" integer,
	"SCORE_CLIENT" integer DEFAULT '0'
) WITH (
  OIDS=FALSE
);







ALTER TABLE "CLIENT_SCORE" ADD CONSTRAINT "CLIENT_SCORE_fk0" FOREIGN KEY ("CODE_CLIENT") REFERENCES "DATA_CUSTOMER"("CODE_CLIENT");
ALTER TABLE "CLIENT_SCORE" ADD CONSTRAINT "CLIENT_SCORE_fk1" FOREIGN KEY ("DATA_CREDIT_PK") REFERENCES "DATA_CREDIT"("DATA_CREDIT_PK");
ALTER TABLE "CLIENT_SCORE" ADD CONSTRAINT "CLIENT_SCORE_fk2" FOREIGN KEY ("DATA_ACCOUNT_PK") REFERENCES "DATA_ACCOUNT"("DATA_ACCOUNT_PK");
ALTER TABLE "CLIENT_SCORE" ADD CONSTRAINT "CLIENT_SCORE_fk3" FOREIGN KEY ("DATA_NBR_MVT_PK") REFERENCES "DATA_NBR_MVT"("DATA_NBR_MVT_PK");
